// Generated by https://quicktype.io

export interface IULBProfileRequestResponse {
  timestamp: number;
  success: boolean;
  message: string;
  data: IULBProfileRequest[];
}

export interface IULBProfileRequest {
  _id: string;
  ulbType: null | string;
  natureOfUlb: null;
  name: null | string;
  regionalName: null;
  code: null;
  state: null;
  wards: number | null;
  area: null;
  population: null;
  location: null;
  amrut: null;
  commissionerName?: null | string;
  commissionerEmail?: string;
  commissionerConatactNumber?: string;
  accountantName?: string;
  accountantEmail?: string;
  accountantConatactNumber?: string;
  status: string;
  history: any[];
  modifiedAt: string;
  createdAt: string;
  isActive: boolean;
  ulb: string;
  actionTakenBy: string;
  __v: number;
}
