enum UPLOAD_STATUS {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  NA = 'NA'
}

const REQUEST_STATUS = {...UPLOAD_STATUS, CANCELLED: 'CANCELLED'};
const ULBSIGNUPSTATUS = UPLOAD_STATUS;

export {UPLOAD_STATUS, REQUEST_STATUS, ULBSIGNUPSTATUS};
