enum UPLOAD_STATUS {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED"
}

const REQUEST_STATUS = { ...UPLOAD_STATUS, CANCELLED: "CANCELLED" };

export { UPLOAD_STATUS, REQUEST_STATUS };
