export enum fieldNameWithFileRequirement {
  TYPE = "type",
  NoOfWards = "noOfWards",
  Population = "population",
  Area = "area",
  Name = "name",
}

// tslint:disable-next-line: interface-over-type-literal
export type FieldsWithFile = {
  [key in fieldNameWithFileRequirement]?: { file: File };
};
// Generated by https://quicktype.io

export interface IULBProfileData {
  mobile: string;
  _id: string;
  email: string;
  name: string;
  accountantConatactNumber: string;
  accountantEmail: string;
  accountantName: string;
  commissionerConatactNumber: string;
  commissionerEmail: string;
  commissionerName: string;
  status: ULBSignupSTATUS;
  ulb: Ulb;
}

export interface Ulb {
  wards: number;
  area: number;
  population: number;
  _id: string;
  code: string;
  name: string;
  state: State;
}

export interface State {
  _id: string;
  name: string;
  code: string;
}

export type ULBSignupSTATUS = "APPROVED" | "REJECTED" | "PENDING";
