// Generated by https://quicktype.io
import { USER_TYPE } from 'src/app/models/user/userType';
import { UPLOAD_STATUS } from 'src/app/util/enums';

export interface IFinancialData {
  ulb: string;
  waterManagement: WaterManagement;
  solidWasteManagement: SolidWasteManagement;
  millionPlusCities: MillionPlusCities;
  isCompleted?: boolean;
  status?: UPLOAD_STATUS;
  actionTakenByUserRole?: USER_TYPE;
  actionTakenByUserName?: string;
}

export interface MillionPlusCities {
  documents: MillionPlusCitiesDocuments;
}

export interface MillionPlusCitiesDocuments {
  cityPlan: CityPlan[];
  waterBalancePlan: CityPlan[];
  serviceLevelPlan: CityPlan[];
  solidWastePlan: CityPlan[];
}

export interface CityPlan {
  url: string;
  name: string;
}

export enum URL {
  Abc = "ABC",
  Xyz = "XYZ",
}

export interface SolidWasteManagement {
  documents: SolidWasteManagementDocuments;
}

export interface SolidWasteManagementDocuments {
  garbageFreeCities: CityPlan[];
  waterSupplyCoverage: CityPlan[];
}

export interface WaterManagement {
  serviceLevel: HouseHoldCoveredPipedSupply;
  houseHoldCoveredPipedSupply: HouseHoldCoveredPipedSupply;
  waterSuppliedPerDay: HouseHoldCoveredPipedSupply;
  reduction: HouseHoldCoveredPipedSupply;
  houseHoldCoveredWithSewerage: HouseHoldCoveredPipedSupply;
  documents: WaterManagementDocuments;
}

export interface WaterManagementDocuments {
  wasteWaterPlan: CityPlan[];
}

export interface HouseHoldCoveredPipedSupply {
  benchmark: string;
  baseline: Baseline;
  target: { [key: string]: string };
}

export interface Baseline {
  "2021": string;
}
