name: Build and Deploy
on:
  push:
    branches:
      - main  # Adjust this to match your main branch name

jobs:
  test-ssh-connection:
    runs-on: ubuntu-latest

    steps:
    - name: Test SSH connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22  # Change this if your SSH server uses a different port
        script: 'echo "SSH connection successful."'