name: Build and Deploy

on:
  pull_request:
    types: 
      - closed
    branches: 
      - "dev-jana" 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get code
      uses: actions/checkout@v3
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: npm install --force
    - name: Install dependencies
      run: npm install --save @types/lodash@4.14.74 --force

    - name: Build Angular project
      run: npm run build 

    # - name: Copy dist files to server
    #   uses: appleboy/scp-action@master
    #   with:
    #     host: ${{ secrets.SERVER_IP }}  # Add your server IP address as a secret in your repository
    #     username: ${{ secrets.SERVER_USERNAME }}  # Add your server username as a secret
    #     key: ${{ secrets.SERVER_SSH_KEY }}  # Add your server SSH private key as a secret
    #     source: "dist/*"  # Adjust this path based on your project structure
    #     target: "/var/www/html/dev-jana/citifinance-ng-ui/dist/PerfectAngular/"  # Specify the destination path on your server